"$schema" = 'https://starship.rs/config-schema.json'
add_newline = true
format = "$os$directory$container$git_branch $git_status$python$nodejs$lua$rust$java$c$golang$cmd_duration$status$line_break[❯ ](bold sky)"
continuation_prompt = "∙  ┆ "
palette = "catppuccin_mocha"
[line_break]
disabled = false
[status]
symbol = "✗"
not_found_symbol = "󰍉 Not Found"
not_executable_symbol = " Can't Execute E"
sigint_symbol = "󰂭 "
signal_symbol = "󱑽 "
success_symbol = ""
format = "[$symbol](fg:red)"
map_symbol = true
disabled = false
[cmd_duration]
min_time = 1000
format = "[$duration](fg:yellow)"
[container]
symbol = " 󰏖"
format = "[$symbol ](yellow dimmed)"
[directory]
format = " [](fg:surface0)[$path](bg:surface0 fg:text)[](fg:surface0) [$read_only](fg:yellow)"
read_only = " "
truncate_to_repo = true
truncation_length = 4
truncation_symbol = ""
[git_branch]
symbol = ""
style = ""
format = "[ $symbol $branch](fg:lavender)(:$remote_branch)"
[os]
disabled = false
format = "$symbol"
[os.symbols]
Arch = "[ ](fg:sky)"
Alpine = "[](fg:sky)"
Debian = "[](fg:red)"
EndeavourOS = "[](fg:lavender)"
Fedora = "[](fg:blue)"
NixOS = "[](fg:blue)"
openSUSE = "[](fg:green)"
SUSE = "[](fg:green)"
Ubuntu = "[](fg:lavender)"
Macos = "[](fg:white)"
[python]
symbol = ""
format = "[$symbol ](yellow)"
[nodejs]
symbol = "󰛦"
format = "[$symbol ](sky)"
[bun]
symbol = "󰛦"
format = "[$symbol ](blue)"
[deno]
symbol = "󰛦"
format = "[$symbol ](blue)"
[lua]
symbol = "󰢱"
format = "[$symbol ](blue)"
[rust]
symbol = ""
format = "[$symbol ](red)"
[java]
symbol = ""
format = "[$symbol ](red)"
[c]
symbol = ""
format = "[$symbol ](blue)"
[golang]
symbol = ""
format = "[$symbol ](blue)"
[dart]
symbol = ""
format = "[$symbol ](blue)"
[elixir]
symbol = ""
format = "[$symbol ](lavender)"
[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
